# Generated by Django 5.2.17 on 2026-10-02 00:23

import core.utils
from django.db import migrations


def encrypt_existing(apps, schema_editor):
    """Re-grava as linhas existentes: valores legados em texto puro passam a ficar cifrados."""
    Model = apps.get_model('emails', 'MailBox')
    for obj in Model.objects.all().iterator():
        obj.save(update_fields=['password'])


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailbox",
            name="password",
            field=core.utils.EncryptedTextField(),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
