# Generated by Django 5.2.17 on 2026-10-06 12:38

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_customuser_must_change_password"),
        ("contacts", "0001_initial"),
        ("emails", "0002_encrypt_secrets"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTriage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("intimacao", "Intimação / tribunal"),
                            ("cliente", "Mensagem de cliente"),
                            ("agenda", "Audiência, reunião ou compromisso"),
                            ("financeiro", "Financeiro (boleto, pagamento, nota)"),
                            ("comercial", "Novo cliente / proposta"),
                            ("documento", "Envio de documento"),
                            ("marketing", "Propaganda / newsletter"),
                            ("outro", "Outro"),
                        ],
                        db_index=True,
                        default="outro",
                        max_length=12,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=6,
                    ),
                ),
                ("summary", core.utils.EncryptedTextField(blank=True, default="")),
                (
                    "suggested_action",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("method", models.CharField(default="regras", max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contacts.contact",
                    ),
                ),
                (
                    "email",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="triage",
                        to="emails.emailmessage",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_triages",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
