# Generated by Django 5.2.12 on 2026-03-23 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_automationrule'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='automationrule',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='extraction_profile',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='mailbox',
        ),
        migrations.RemoveField(
            model_name='automationrule',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='emailmessage',
            name='emails_emai_status_c5f0b2_idx',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='extracted_data',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='last_processed_at',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='processing_attempts',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='extraction_profile',
        ),
        migrations.RemoveField(
            model_name='mailbox',
            name='integration_config',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='is_dispatched',
            field=models.BooleanField(default=False, verbose_name='Despachado para o Orquestrador?'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='mailbox',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='emails.mailbox'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(help_text='ID único do email (para evitar duplicidade)', max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['is_dispatched', 'received_at'], name='emails_emai_is_disp_e7ecd3_idx'),
        ),
        migrations.DeleteModel(
            name='AutomationRule',
        ),
    ]
