# Generated by Django 5.2.17 on 2026-10-05 12:15

import core.pii
import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cliente", "Cliente"),
                            ("parte_contraria", "Parte contrária"),
                            ("testemunha", "Testemunha"),
                            ("perito", "Perito"),
                            ("correspondente", "Correspondente"),
                            ("fornecedor", "Fornecedor"),
                            ("outro", "Outro"),
                        ],
                        db_index=True,
                        default="cliente",
                        max_length=20,
                    ),
                ),
                (
                    "person_type",
                    models.CharField(
                        choices=[("PF", "Pessoa física"), ("PJ", "Pessoa jurídica")],
                        default="PF",
                        max_length=2,
                    ),
                ),
                ("name", core.utils.EncryptedTextField()),
                ("name_idx", models.TextField(blank=True, default="", editable=False)),
                ("document", core.utils.EncryptedTextField(blank=True, default="")),
                (
                    "document_bidx",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                ("email", core.utils.EncryptedTextField(blank=True, default="")),
                (
                    "email_bidx",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                ("phone", core.utils.EncryptedTextField(blank=True, default="")),
                (
                    "phone_bidx",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                ("notes", core.utils.EncryptedTextField(blank=True, default="")),
                ("tags", models.JSONField(blank=True, default=list)),
                ("whatsapp_consent", models.BooleanField(default=False)),
                ("email_consent", models.BooleanField(default=False)),
                ("consent_updated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consent_source",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("opted_out", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Cadastro manual"),
                            ("import", "Importação"),
                            ("extraction", "Leitura de documento"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("document_bidx__isnull", False)),
                        fields=("organization", "document_bidx"),
                        name="uniq_contact_document_per_org",
                    )
                ],
            },
            bases=(core.pii.PIIIndexMixin, models.Model),
        ),
    ]
