# Generated by Django 5.2.17 on 2026-10-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="birthday",
            field=models.CharField(blank=True, db_index=True, default="", max_length=5),
        ),
        migrations.AlterField(
            model_name="contact",
            name="source",
            field=models.CharField(
                choices=[
                    ("manual", "Cadastro manual"),
                    ("import", "Importação"),
                    ("extraction", "Leitura de documento"),
                    ("form", "Formulário de captação"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
    ]
