# Generated by Django 5.2.14 on 2026-10-01 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_member_credits'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCreditUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_cycle_month', models.DateField(verbose_name='Mês de Faturação')),
                ('credits_used', models.PositiveIntegerField(default=0, verbose_name='Créditos usados')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_usage', to='accounts.organizationmembership')),
            ],
            options={
                'verbose_name': 'Uso de créditos do membro',
                'verbose_name_plural': 'Uso de créditos dos membros',
                'unique_together': {('membership', 'billing_cycle_month')},
            },
        ),
    ]
