# Generated by Django 5.2.17 on 2026-10-04 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_subscription_state"),
        ("billing", "0002_member_credits"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("credits", models.PositiveIntegerField()),
                ("price_brl", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["price_brl"],
            },
        ),
        migrations.CreateModel(
            name="CreditLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits_total", models.PositiveIntegerField()),
                ("credits_remaining", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField()),
                ("stripe_session_id", models.CharField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_lots",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["expires_at", "id"],
            },
        ),
    ]
