# Generated by Django 5.2.17 on 2026-10-04 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_backfill_pii"),
        ("billing", "0003_subscription_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("body", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Informativo"),
                            ("warn", "Atenção"),
                            ("danger", "Urgente"),
                        ],
                        default="info",
                        max_length=8,
                    ),
                ),
                (
                    "audience_tiers",
                    models.JSONField(
                        blank=True, default=list, help_text="Vazio = todos os planos."
                    ),
                ),
                (
                    "audience_statuses",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ex.: ["trialing","past_due"]. Vazio = todos.',
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CreditWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.SlugField(max_length=40, unique=True)),
                ("label", models.CharField(max_length=80)),
                ("credits", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["operation"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=40, unique=True)),
                ("name", models.CharField(max_length=80)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("percent", "Percentual (%)"),
                            ("amount", "Valor fixo (R$)"),
                        ],
                        default="percent",
                        max_length=8,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "duration",
                    models.CharField(
                        choices=[
                            ("once", "Só na primeira cobrança"),
                            ("repeating", "Por N meses"),
                            ("forever", "Para sempre"),
                        ],
                        default="once",
                        max_length=10,
                    ),
                ),
                (
                    "duration_months",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "plan_tiers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ex.: ["START","PRO"]. Vazio = todos os planos.',
                    ),
                ),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("max_redemptions", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "redemptions_count",
                    models.PositiveIntegerField(default=0, editable=False),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "stripe_coupon_id",
                    models.CharField(blank=True, editable=False, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="creditlot",
            name="amount_paid_cents",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="PlanPriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("old_credits", models.IntegerField()),
                ("new_credits", models.IntegerField()),
                ("changed_by", models.CharField(blank=True, max_length=64)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="billing.subscriptionplan",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stripe_session_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="promotion_redemptions",
                        to="accounts.organization",
                    ),
                ),
                (
                    "promotion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="billing.promotion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("promotion", "organization"), name="uniq_promo_per_org"
                    )
                ],
            },
        ),
    ]
