# Generated by Django 5.2.17 on 2026-10-05 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_mfa"),
        ("billing", "0004_finance_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("subscription", "Assinatura"),
                            ("credit_pack", "Pacote de créditos"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("amount_cents", models.PositiveIntegerField()),
                ("paid_at", models.DateTimeField(db_index=True)),
                ("stripe_id", models.CharField(max_length=100, unique=True)),
                (
                    "invoice_status",
                    models.CharField(
                        choices=[
                            ("pending", "NF pendente"),
                            ("issued", "NF emitida"),
                            ("not_required", "Sem NF"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("invoice_issued_at", models.DateField(blank=True, null=True)),
                (
                    "invoice_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-id"],
            },
        ),
    ]
