# Generated by Django 5.2.17 on 2026-10-05 17:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_payment_ledger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FiscalObligation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=30, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "periodicity",
                    models.CharField(
                        choices=[("mensal", "Mensal"), ("anual", "Anual")],
                        default="mensal",
                        max_length=6,
                    ),
                ),
                ("due_day", models.PositiveSmallIntegerField(default=20)),
                ("due_month", models.PositiveSmallIntegerField(default=3)),
                (
                    "adjust",
                    models.CharField(
                        choices=[
                            ("antecipa", "Antecipa para o dia útil anterior"),
                            ("posterga", "Posterga para o próximo dia útil"),
                            ("ultimo_util", "Último dia útil do mês"),
                        ],
                        default="antecipa",
                        max_length=12,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["due_day", "code"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="nfse_error",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="payment",
            name="nfse_ref",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="nfse_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="payment",
            name="invoice_status",
            field=models.CharField(
                choices=[
                    ("pending", "NF pendente"),
                    ("processing", "NFS-e em processamento"),
                    ("issued", "NF emitida"),
                    ("error", "NFS-e com erro"),
                    ("canceled", "NF cancelada"),
                    ("not_required", "Sem NF"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FiscalObligationDone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("competence", models.CharField(max_length=7)),
                ("done_at", models.DateTimeField(auto_now_add=True)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "done_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obligation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="done",
                        to="billing.fiscalobligation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("obligation", "competence"),
                        name="uniq_obligation_competence",
                    )
                ],
            },
        ),
    ]
