# Generated by Django 5.2.17 on 2026-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_fiscal_obligations_seed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="promotion",
            name="kind",
            field=models.CharField(
                choices=[
                    ("percent", "Percentual (%)"),
                    ("amount", "Valor fixo (R$)"),
                    ("trial", "Dias extras de teste"),
                ],
                default="percent",
                max_length=8,
            ),
        ),
    ]
