# Generated by Django 5.2.17 on 2026-10-08 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_perfil_capa"),
        ("billing", "0008_alter_promotion_kind"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAddon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("contratado", "Contratado"),
                            ("cortesia", "Cortesia da Gestão"),
                        ],
                        default="contratado",
                        max_length=12,
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_addon",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
    ]
