# Generated by Django 5.2.17 on 2026-10-05 17:08

import core.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("minutas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="draft",
            name="generated_content",
            field=core.utils.EncryptedTextField(blank=True, default=""),
        ),
    ]
