# Generated by Django 5.2.17 on 2026-10-02 19:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ComplianceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("framework", models.CharField(db_index=True, max_length=16)),
                ("score", models.FloatField()),
                ("counts", models.JSONField(default=dict)),
                ("failing", models.JSONField(default=list)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ControlAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("framework", models.CharField(db_index=True, max_length=16)),
                ("control_id", models.CharField(max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("implemented", "Implementado"),
                            ("partial", "Parcial"),
                            ("not_implemented", "Não implementado"),
                            ("not_applicable", "Não aplicável"),
                            ("not_assessed", "Não avaliado"),
                        ],
                        default="not_assessed",
                        max_length=16,
                    ),
                ),
                (
                    "owner",
                    models.CharField(
                        blank=True,
                        help_text="Responsável pelo controle.",
                        max_length=120,
                    ),
                ),
                (
                    "evidence_url",
                    models.CharField(
                        blank=True,
                        help_text="Link/documento que comprova.",
                        max_length=500,
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, help_text='Obrigatória para "Não aplicável".'
                    ),
                ),
                ("reviewed_by", models.CharField(blank=True, max_length=64)),
                (
                    "reviewed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("next_review_at", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["framework", "control_id"],
                "unique_together": {("framework", "control_id")},
            },
        ),
    ]
