# Generated by Django 5.2.12 on 2026-04-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0002_extractionprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionprofile',
            name='ai_provider',
            field=models.CharField(choices=[('OPENAI', 'OpenAI (GPT-3.5/GPT-4)'), ('GEMINI', 'Google Gemini (1.5 Flash)'), ('GROQ', 'Llama 3 (via Groq)')], default='OPENAI', max_length=20, verbose_name='Motor de IA'),
        ),
    ]
