# Generated by Django 5.2.17 on 2026-10-02 19:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationOffboarding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_id", models.UUIDField(db_index=True)),
                ("organization_name", models.CharField(max_length=255)),
                ("requested_by", models.CharField(max_length=64)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("purge_after", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Em período de recuperação"),
                            ("cancelled", "Cancelado (conta recuperada)"),
                            ("purged", "Eliminado"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("purged_at", models.DateTimeField(blank=True, null=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="SubprocessorEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("country", models.CharField(max_length=60)),
                ("purpose", models.CharField(max_length=255)),
                ("data_categories", models.JSONField(default=list)),
                ("international_transfer", models.BooleanField(default=True)),
                (
                    "safeguards",
                    models.CharField(
                        blank=True,
                        help_text="Ex.: cláusulas-padrão, DPA assinado.",
                        max_length=255,
                    ),
                ),
                ("dpa_url", models.URLField(blank=True)),
                (
                    "contract_verified",
                    models.BooleanField(
                        default=False, help_text="DPA/contrato conferido pelo jurídico."
                    ),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataSubjectRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_ref", models.CharField(db_index=True, max_length=64)),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("access", "Confirmação/acesso aos dados"),
                            ("correction", "Correção"),
                            ("anonymization", "Anonimização, bloqueio ou eliminação"),
                            ("portability", "Portabilidade"),
                            ("info_sharing", "Informação sobre compartilhamento"),
                            ("revoke_consent", "Revogação de consentimento"),
                            ("deletion", "Eliminação da conta"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("in_progress", "Em atendimento"),
                            ("fulfilled", "Atendido"),
                            ("rejected", "Recusado (justificado)"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("due_at", models.DateTimeField()),
                ("fulfilled_at", models.DateTimeField(blank=True, null=True)),
                ("handled_by", models.CharField(blank=True, max_length=64)),
                ("resolution", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="privacy_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="LegalDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("terms", "Termos de Uso"),
                            ("privacy", "Política de Privacidade"),
                            ("ciencia", "Termo de Ciência de Tratamento de Dados"),
                            ("ai_notice", "Aviso sobre Inteligência Artificial"),
                            ("dpa", "Cláusula do Controlador / DPA"),
                        ],
                        max_length=16,
                    ),
                ),
                ("version", models.CharField(max_length=16)),
                ("title", models.CharField(max_length=200)),
                ("content_md", models.TextField()),
                ("content_sha256", models.CharField(editable=False, max_length=64)),
                ("locale", models.CharField(default="pt-BR", max_length=8)),
                (
                    "requires_reconsent",
                    models.BooleanField(
                        default=True,
                        help_text="Exige novo aceite de quem aceitou versões anteriores.",
                    ),
                ),
                ("is_current", models.BooleanField(db_index=True, default=False)),
                (
                    "needs_legal_review",
                    models.BooleanField(
                        default=True,
                        help_text="Rascunho: revisão por advogado/DPO pendente.",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["kind", "-published_at"],
                "unique_together": {("kind", "version")},
            },
        ),
        migrations.CreateModel(
            name="ConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_ref",
                    models.CharField(
                        db_index=True,
                        help_text="ID do utilizador (preservado após anonimização).",
                        max_length=64,
                    ),
                ),
                ("organization_id", models.UUIDField(blank=True, null=True)),
                ("purpose", models.CharField(default="essential", max_length=64)),
                ("legal_basis", models.CharField(default="contrato", max_length=32)),
                ("granted", models.BooleanField(default=True)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent_hash", models.CharField(blank=True, max_length=16)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("checkbox", "Caixa de seleção"),
                            ("click", "Clique em aceitar"),
                            ("api", "API"),
                        ],
                        default="checkbox",
                        max_length=10,
                    ),
                ),
                ("evidence_sha256", models.CharField(max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consents",
                        to="privacy.legaldocument",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "indexes": [
                    models.Index(
                        fields=["user_ref", "document"],
                        name="privacy_con_user_re_8e7792_idx",
                    )
                ],
            },
        ),
    ]
