# Generated by Django 5.2.17 on 2026-10-04 17:08

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0012_backfill_pii"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutonomyProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_kind", models.CharField(max_length=40)),
                ("from_mode", models.CharField(max_length=12)),
                ("to_mode", models.CharField(max_length=12)),
                ("samples", models.PositiveIntegerField()),
                ("approval_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberta"),
                            ("approved", "Aprovada"),
                            ("rejected", "Recusada"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autonomy_proposals",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_kind", models.CharField(db_index=True, max_length=40)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("approved", "Aprovou sem editar"),
                            ("edited", "Editou e aprovou"),
                            ("rejected", "Rejeitou"),
                            ("undone", "Desfez depois"),
                        ],
                        max_length=10,
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=60)),
                ("changes", core.utils.EncryptedJSONField(blank=True, default=list)),
                ("confidence", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_feedback",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "action_kind", "-created_at"],
                        name="brain_aifee_organiz_361af8_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AutonomyLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_kind", models.CharField(max_length=40)),
                ("mode", models.CharField(default="review", max_length=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="autonomy_levels",
                        to="accounts.organization",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "action_kind"),
                        name="uniq_autonomy_level",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MemoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("extraction_example", "Exemplo de leitura aprovada"),
                            ("template", "Modelo de peça"),
                            ("note", "Anotação do escritório"),
                            ("decision", "Decisão/entendimento"),
                        ],
                        max_length=24,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=160)),
                ("text", core.utils.EncryptedTextField()),
                ("payload", core.utils.EncryptedJSONField(blank=True, default=dict)),
                ("embedding", core.utils.EncryptedJSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, default="", max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memory_items",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "kind", "-created_at"],
                        name="brain_memor_organiz_b1e788_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OfficeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(default="field_correction", max_length=24)),
                ("field", models.CharField(max_length=60)),
                ("from_value", models.CharField(max_length=120)),
                ("to_value", models.CharField(max_length=120)),
                ("evidence", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("proposed", "Proposta"),
                            ("active", "Ativa"),
                            ("rejected", "Rejeitada"),
                            ("disabled", "Desligada"),
                        ],
                        default="proposed",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_rules",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "organization",
                            "kind",
                            "field",
                            "from_value",
                            "to_value",
                        ),
                        name="uniq_office_rule",
                    )
                ],
            },
        ),
    ]
