# Generated by Django 5.2.17 on 2026-10-05 17:08

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_mfa"),
        ("automations", "0002_alter_rule_trigger"),
        ("brain", "0001_brain"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="memoryitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("extraction_example", "Exemplo de leitura aprovada"),
                    ("template", "Modelo de peça"),
                    ("note", "Anotação do escritório"),
                    ("decision", "Decisão/entendimento"),
                    ("draft_example", "Minuta revisada"),
                    ("marketing_example", "Conteúdo de marketing aprovado"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="OfficeProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("areas", models.JSONField(blank=True, default=list)),
                ("audience", models.CharField(blank=True, default="", max_length=200)),
                ("city", models.CharField(blank=True, default="", max_length=80)),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("formal", "Formal"),
                            ("proximo", "Próximo e acolhedor"),
                            ("didatico", "Didático"),
                        ],
                        default="formal",
                        max_length=10,
                    ),
                ),
                ("signature", models.TextField(blank=True, default="")),
                ("social", models.JSONField(blank=True, default=dict)),
                ("auto_stats", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_profile",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AutomationSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=80)),
                ("title", models.CharField(max_length=160)),
                ("reason", core.utils.EncryptedTextField()),
                ("evidence", models.PositiveIntegerField(default=0)),
                ("payload", core.utils.EncryptedJSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberta"),
                            ("accepted", "Aceita"),
                            ("dismissed", "Dispensada"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                    ),
                ),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_suggestions",
                        to="accounts.organization",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="automations.rule",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "key"), name="uniq_suggestion_per_org"
                    )
                ],
            },
        ),
    ]
