# Generated by Django 5.2.17 on 2026-10-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brain", "0002_alter_memoryitem_kind_officeprofile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeprofile",
            name="brand_color",
            field=models.CharField(blank=True, default="#1d4ed8", max_length=7),
        ),
        migrations.AddField(
            model_name="officeprofile",
            name="email_layout",
            field=models.CharField(blank=True, default="moderno", max_length=12),
        ),
    ]
