# Generated by Django 5.2.17 on 2026-10-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brain", "0003_email_visual"),
    ]

    operations = [
        migrations.AddField(
            model_name="officeprofile",
            name="email_logo",
            field=models.TextField(blank=True, default=""),
        ),
    ]
