"""RoPA — Registro das Operações de Tratamento de Dados Pessoais (LGPD art. 37 / ISO 27701 7.2.8).

Mantido em código (revisado em PR) para ficar sempre sincronizado com o que o sistema realmente faz.
Papéis: ``controlador`` = Cadrius decide finalidade (dados de quem usa a plataforma);
``operador`` = o escritório decide (dados de terceiros nos e-mails/mensagens/webhooks).
"""

PROCESSING_ACTIVITIES = [
    {
        'id': 'PA-01', 'name': 'Cadastro e autenticação de usuários', 'role': 'controlador',
        'purpose': 'Criar e proteger contas; identificar advogados e equipe.',
        'legal_basis': 'Execução de contrato (art. 7º, V)',
        'data_subjects': 'Advogados e equipe dos escritórios',
        'data_categories': ['identificacao (nome, e-mail, CPF, OAB)', 'contato (telefone)', 'credenciais (hash de senha)'],
        'sources': 'Titular / SSO (Google, Microsoft)', 'recipients': 'Google/Microsoft (SSO) — quando usado',
        'international_transfer': 'Sim (SSO), com salvaguardas', 'retention': 'Enquanto a conta existir; anonimização no encerramento',
        'security': 'Hash de senha, rate limit, bloqueio por tentativas, JWT com revogação, auditoria',
    },
    {
        'id': 'PA-02', 'name': 'Gestão de escritórios, equipe e planos', 'role': 'controlador',
        'purpose': 'Organizar escritórios, cargos (RBAC), limites do plano e cobrança.',
        'legal_basis': 'Execução de contrato (art. 7º, V)',
        'data_subjects': 'Representantes dos escritórios',
        'data_categories': ['dados cadastrais da empresa (CNPJ, razão social, endereço)', 'cargo/permissões', 'plano contratado'],
        'sources': 'Titular', 'recipients': 'Stripe (cobrança)',
        'international_transfer': 'Sim (Stripe), com salvaguardas', 'retention': 'Contrato + 30 dias após encerramento',
        'security': 'Isolamento por escritório, RBAC, auditoria de convites e mudanças de cargo',
    },
    {
        'id': 'PA-03', 'name': 'Leitura de caixas de e-mail (IMAP) e armazenamento de mensagens', 'role': 'operador',
        'purpose': 'Capturar e-mails do escritório para gatilhos de automação e extração.',
        'legal_basis': 'Definida pelo controlador (escritório) — ver cláusula de responsabilidade',
        'data_subjects': 'Clientes, partes e contrapartes citados nos e-mails',
        'data_categories': ['conteúdo de comunicações', 'dados processuais (podem incluir dados sensíveis)', 'identificação de remetentes'],
        'sources': 'Caixa de e-mail do escritório', 'recipients': 'Provedores de IA (PA-04)',
        'international_transfer': 'Sim (via IA)', 'retention': 'Corpo: 90 dias após processado',
        'security': 'Senha IMAP cifrada (Fernet), acesso por escritório, leitura de e-mail registrada na trilha',
    },
    {
        'id': 'PA-04', 'name': 'Extração e geração de automações por IA', 'role': 'operador',
        'purpose': 'Extrair dados estruturados (processo, prazos) e gerar rascunhos de workflows.',
        'legal_basis': 'Definida pelo controlador; execução de contrato com o escritório',
        'data_subjects': 'Titulares presentes no conteúdo analisado',
        'data_categories': ['trechos de conteúdo (limitados a 20 mil caracteres)', 'dados extraídos (JSON)'],
        'sources': 'PA-03, webhooks, texto do usuário', 'recipients': 'OpenAI, Google (Gemini), Groq — conforme política do escritório',
        'international_transfer': 'Sim (EUA)', 'retention': 'Provedor: conforme DPA; Cadrius: payload 90 dias',
        'security': 'Política de IA por escritório, kill switch, texto delimitado contra prompt injection, humano no circuito, registro sem conteúdo',
    },
    {
        'id': 'PA-05', 'name': 'Execução de automações e envio de mensagens (WhatsApp/e-mail/webhook)', 'role': 'operador',
        'purpose': 'Notificar clientes e integrar sistemas conforme workflows aprovados.',
        'legal_basis': 'Definida pelo controlador (escritório)',
        'data_subjects': 'Clientes do escritório',
        'data_categories': ['contato (telefone/e-mail)', 'conteúdo da mensagem', 'status de entrega'],
        'sources': 'Workflows', 'recipients': 'Meta/WhatsApp (Evolution API), sistemas de destino do escritório',
        'international_transfer': 'Sim (WhatsApp)', 'retention': 'Payload/resultado 90 dias; logs de integração 30 dias',
        'security': 'Bloqueio de SSRF, escape de template, confirmação humana de ações de origem IA, auditoria',
    },
    {
        'id': 'PA-06', 'name': 'Recepção de webhooks externos', 'role': 'operador',
        'purpose': 'Receber eventos de tribunais, gateways e CRMs e disparar workflows.',
        'legal_basis': 'Definida pelo controlador (escritório)',
        'data_subjects': 'Titulares presentes nos payloads',
        'data_categories': ['payload bruto do evento'],
        'sources': 'Sistemas externos', 'recipients': 'Workflows do escritório',
        'international_transfer': 'Não', 'retention': '90 dias',
        'security': 'Token por URL, rate limit, tamanho máximo, registro de tokens inválidos',
    },
    {
        'id': 'PA-07', 'name': 'Segurança, auditoria e detecção de anomalias', 'role': 'controlador',
        'purpose': 'Registrar acessos e ações, detectar fraudes e atender obrigações de segurança.',
        'legal_basis': 'Legítimo interesse (art. 7º, IX) e obrigação legal (Marco Civil, art. 15)',
        'data_subjects': 'Todos os usuários',
        'data_categories': ['IP', 'hash do navegador', 'ações realizadas', 'e-mail mascarado'],
        'sources': 'Uso da plataforma', 'recipients': 'Sentry (erros, sem PII automática)',
        'international_transfer': 'Sim (Sentry)', 'retention': '12 meses (trilha) — sem conteúdo pessoal',
        'security': 'Trilha imutável e encadeada, trigger no banco, redação de PII',
    },
    {
        'id': 'PA-08', 'name': 'Backups e continuidade', 'role': 'controlador/operador',
        'purpose': 'Restaurar o serviço em caso de falha.',
        'legal_basis': 'Legítimo interesse e execução de contrato',
        'data_subjects': 'Todos',
        'data_categories': ['todos os dados da base'],
        'sources': 'Banco de dados', 'recipients': 'Supabase (armazenamento cifrado)',
        'international_transfer': 'Sim (EUA)', 'retention': '7 dias (local) / conforme bucket',
        'security': 'Dump cifrado com Fernet antes do upload, diretório temporário 0700',
    },
    {
        'id': 'PA-09', 'name': 'Direitos do titular e consentimentos', 'role': 'controlador',
        'purpose': 'Atender pedidos do art. 18 e comprovar aceites.',
        'legal_basis': 'Obrigação legal (art. 7º, II)',
        'data_subjects': 'Usuários',
        'data_categories': ['pedidos do titular', 'registros de consentimento (versão, hash, data, IP)'],
        'sources': 'Titular', 'recipients': 'Nenhum',
        'international_transfer': 'Não', 'retention': 'Prova de consentimento mantida pelo prazo prescricional',
        'security': 'Registros append-only; exportação restrita ao próprio titular',
    },
]
