# Generated by Django 5.2.12 on 2026-03-23 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome da Automação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário (Escritório)')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': 'Workflows',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('WEBHOOK', 'Webhook (Sistema Jurídico/Externo)'), ('EMAIL', 'Recebimento de E-mail'), ('SCHEDULE', 'Agendamento (Cron)'), ('MANUAL', 'Execução Manual')], max_length=50)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações específicas do gatilho em formato JSON')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trigger', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Sucesso'), ('FAILED', 'Falha'), ('PENDING_REVIEW', 'Aguardando Revisão Humana')], max_length=20)),
                ('trigger_payload', models.JSONField(blank=True, null=True)),
                ('final_result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.PositiveIntegerField(blank=True, help_text='Tempo de execução em milissegundos para cálculo de ROI', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workflow', 'status'], name='workflows_e_workflo_2441db_idx'), models.Index(fields=['created_at'], name='workflows_e_created_bfed85_idx')],
            },
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('AI_EXTRACTION', 'Extrair Dados com IA (Gemini/ChatGPT)'), ('CREATE_TASK', 'Criar Tarefa (Gestão Ágil)'), ('SEND_WHATSAPP', 'Enviar Notificação (WhatsApp)'), ('SHEETS_INSERT', 'Adicionar Linha (Planilha)')], max_length=50)),
                ('order', models.PositiveIntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Configurações de execução e mapeamento de campos')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['workflow', 'order'],
                'unique_together': {('workflow', 'order')},
            },
        ),
    ]
