# Generated by Django 5.2.12 on 2026-04-01 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0004_appconnection_remove_integrationconfig_user_and_more'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='workflow',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='config',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='trigger_type',
        ),
        migrations.RemoveField(
            model_name='workflow',
            name='user',
        ),
        migrations.AddField(
            model_name='action',
            name='connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='integrations.appconnection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='payload_template',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trigger',
            name='connection',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='integrations.appconnection'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trigger',
            name='event_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trigger',
            name='payload_mapping',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.RemoveField(
            model_name='action',
            name='config',
        ),
    ]
