# Generated by Django 6.0.4 on 2026-06-03 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0003_alter_executionlog_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='executionlog',
            name='triggered_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Utilizador autenticado ou proprietário da conexão no momento do disparo.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='workflow_executions',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Disparado por',
            ),
        ),
    ]
