# Generated by Django 5.2.17 on 2026-10-05 12:15

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("contacts", "Contatos"),
                            ("cases", "Processos (monitoramento)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("filename", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Aguardando mapeamento"),
                            ("previewed", "Simulado"),
                            ("done", "Importado"),
                            ("canceled", "Cancelado"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("columns", models.JSONField(default=list)),
                ("rows", core.utils.EncryptedJSONField(blank=True, default=list)),
                ("rows_total", models.PositiveIntegerField(default=0)),
                ("mapping", models.JSONField(blank=True, default=dict)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
