# Generated by Django 5.2.17 on 2026-10-05 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("escritorio", "Escritório"), ("cadrius", "Cadrius")],
                        default="escritorio",
                        max_length=12,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("goal", models.CharField(blank=True, default="", max_length=300)),
                ("audience", models.CharField(blank=True, default="", max_length=200)),
                ("channels", models.JSONField(blank=True, default=list)),
                ("starts_on", models.DateField(blank=True, null=True)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentPiece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("escritorio", "Escritório"), ("cadrius", "Cadrius")],
                        db_index=True,
                        default="escritorio",
                        max_length=12,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("linkedin", "LinkedIn"),
                            ("blog", "Blog / site"),
                            ("google_business", "Perfil no Google"),
                            ("newsletter", "Newsletter (e-mail)"),
                            ("video_curto", "Vídeo curto (Reels/Shorts)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("theme", models.CharField(max_length=200)),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("hashtags", models.JSONField(blank=True, default=list)),
                (
                    "image_hint",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("image_url", models.URLField(blank=True, default="", max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rascunho", "Rascunho"),
                            ("aprovado", "Aprovado"),
                            ("agendado", "Agendado"),
                            ("publicado", "Publicado"),
                            ("falhou", "Falhou"),
                        ],
                        db_index=True,
                        default="rascunho",
                        max_length=10,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "publish_error",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("compliance", models.JSONField(blank=True, default=list)),
                ("generated_body", models.TextField(blank=True, default="")),
                (
                    "ai_provider",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pieces",
                        to="marketing.campaign",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_pieces",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["scope", "organization", "status"],
                        name="marketing_c_scope_d7e435_idx",
                    )
                ],
            },
        ),
    ]
