# Generated by Django 5.2.17 on 2026-10-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_captureform_satisfactionsurvey"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentpiece",
            name="image_file",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
        migrations.AddField(
            model_name="contentpiece",
            name="image_source",
            field=models.CharField(blank=True, default="", max_length=10),
        ),
    ]
