# Generated by Django 5.2.13 on 2026-05-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oab_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da OAB'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oab_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado da OAB (UF)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='practice_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Área de Atuação Principal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='organization',
            name='cep',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='organization',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Sociedade'),
        ),
        migrations.AddField(
            model_name='organization',
            name='corporate_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Corporativo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='main_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone Principal'),
        ),
        migrations.AddField(
            model_name='organization',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='organization',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='organization',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='state_uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)'),
        ),
        migrations.AddField(
            model_name='organization',
            name='street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro'),
        ),
        migrations.AddField(
            model_name='organization',
            name='tax_regime',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Regime Tributário'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='allowed_domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome Interno'),
        ),
    ]
