# Generated by Django 6.0.4 on 2026-06-03 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessageSendCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_count', models.PositiveIntegerField(default=0, verbose_name='Envios WhatsApp')),
                ('email_count', models.PositiveIntegerField(default=0, verbose_name='Envios e-mail')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_send_count', to=settings.AUTH_USER_MODEL, verbose_name='Utilizador')),
            ],
            options={
                'verbose_name': 'Contagem de envios de mensagens',
                'verbose_name_plural': 'Contagens de envios de mensagens',
            },
        ),
    ]
