# Generated by Django 6.0.4 on 2026-06-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermessagesendcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessagesendcount',
            name='automations_run_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Automações executadas'),
        ),
        migrations.AddField(
            model_name='usermessagesendcount',
            name='document_analysis_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Análises de documento'),
        ),
        migrations.AlterModelOptions(
            name='usermessagesendcount',
            options={
                'verbose_name': 'Contagem de uso do utilizador',
                'verbose_name_plural': 'Contagens de uso dos utilizadores',
            },
        ),
    ]
