# Generated by Django 5.2.14 on 2026-10-01 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_usermessagesendcount_dashboard_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='credit_limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Cota mensal de créditos'),
        ),
    ]
