# Generated by Django 5.2.14 on 2026-10-01 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_member_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='next_billing_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima Cobrança'),
        ),
    ]
