# Generated by Django 5.2.14 on 2026-10-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_organization_next_billing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='account_type',
            field=models.CharField(choices=[('PESSOA_FISICA', 'Pessoa Física'), ('EMPRESA', 'Empresa')], default='EMPRESA', max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.AddField(
            model_name='organization',
            name='company_size',
            field=models.CharField(blank=True, choices=[('MEI', 'Microempreendedor Individual'), ('ME', 'Microempresa'), ('EPP', 'Empresa de Pequeno Porte'), ('GRANDE_PORTE', 'Grande Porte')], max_length=20, null=True, verbose_name='Porte da Empresa'),
        ),
        migrations.AddField(
            model_name='organization',
            name='corporate_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Corporativo'),
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='job_title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Cargo'),
        ),
    ]
