# Generated by Django 5.2.17 on 2026-10-04 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_socialidentity"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="current_period_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="past_due_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_customer_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("trialing", "Em teste"),
                    ("active", "Ativa"),
                    ("past_due", "Pagamento pendente"),
                    ("restricted", "Restrita"),
                    ("suspended", "Suspensa"),
                    ("canceled", "Cancelada"),
                ],
                default="active",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="trial_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
