# Generated by Django 5.2.17 on 2026-10-04 15:23

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_subscription_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cpf_bidx",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="name_idx",
            field=models.TextField(blank=True, default="", editable=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="cnpj_bidx",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="cpf",
            field=core.utils.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=core.utils.EncryptedTextField(blank=True, verbose_name="first name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=core.utils.EncryptedTextField(blank=True, verbose_name="last name"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="oab_number",
            field=core.utils.EncryptedTextField(
                blank=True, null=True, verbose_name="Número da OAB"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=core.utils.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="cep",
            field=core.utils.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="cnpj",
            field=core.utils.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="corporate_email",
            field=core.utils.EncryptedTextField(
                blank=True, null=True, verbose_name="E-mail Corporativo"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="corporate_phone",
            field=core.utils.EncryptedTextField(
                blank=True, null=True, verbose_name="Telefone Corporativo"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="main_phone",
            field=core.utils.EncryptedTextField(
                blank=True, null=True, verbose_name="Telefone Principal"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="neighborhood",
            field=core.utils.EncryptedTextField(
                blank=True, null=True, verbose_name="Bairro"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="number",
            field=core.utils.EncryptedTextField(
                blank=True, null=True, verbose_name="Número"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="street",
            field=core.utils.EncryptedTextField(
                blank=True, null=True, verbose_name="Logradouro"
            ),
        ),
    ]
