# Generated by Django 5.2.17 on 2026-10-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_mfa"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="must_change_password",
            field=models.BooleanField(
                default=False, verbose_name="Trocar senha no próximo acesso"
            ),
        ),
    ]
