# Generated by Django 5.2.17 on 2026-10-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_access_groups"),
        ("billing", "0008_alter_promotion_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="pending_promotion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="billing.promotion",
            ),
        ),
    ]
