# Generated by Django 5.2.17 on 2026-10-07 17:10

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_organization_pending_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_signature",
            field=core.utils.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="customuser",
            name="email_signature_image",
            field=models.TextField(blank=True, default=""),
        ),
    ]
