# Generated by Django 5.2.17 on 2026-10-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_email_visual"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="cover_caption",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/covers/",
                verbose_name="Capa do perfil",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="cover_preset",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
