# Generated by Django 5.2.17 on 2026-10-06 13:48

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="category",
            field=models.CharField(
                choices=[
                    ("duvida", "Dúvida"),
                    ("problema", "Problema / erro"),
                    ("financeiro", "Financeiro / assinatura"),
                    ("integracao", "Integração"),
                    ("sugestao", "Sugestão"),
                    ("parametrizacao", "Pedido de parametrização"),
                    ("outro", "Outro"),
                ],
                default="duvida",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CustomizationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("automacao", "Automação / gatilho"),
                            ("integracao", "Integração com outro sistema"),
                            ("relatorio", "Relatório ou painel"),
                            ("modelo", "Modelo de documento / minuta"),
                            ("acessos", "Grupos de acesso da equipe"),
                            ("financeiro", "Financeiro / cobrança"),
                            ("fiscal", "Fiscal / nota fiscal"),
                            ("marketing", "Marketing / captação"),
                            ("importacao", "Importação de dados"),
                            ("tribunais", "Tribunais / prazos"),
                            ("outro", "Outro"),
                        ],
                        max_length=12,
                    ),
                ),
                ("objective", core.utils.EncryptedTextField()),
                ("example", core.utils.EncryptedTextField(blank=True, default="")),
                ("frequency", models.CharField(blank=True, default="", max_length=40)),
                ("users_affected", models.PositiveSmallIntegerField(default=1)),
                ("wanted_by", models.DateField(blank=True, null=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("recebido", "Recebido"),
                            ("em_analise", "Em análise"),
                            ("proposta", "Proposta enviada (aguardando você)"),
                            ("aprovado", "Aprovado pelo escritório"),
                            ("em_execucao", "Em execução"),
                            ("entregue", "Entregue"),
                            ("recusado", "Não será feito"),
                            ("cancelado", "Cancelado pelo escritório"),
                        ],
                        db_index=True,
                        default="recebido",
                        max_length=12,
                    ),
                ),
                ("proposal", core.utils.EncryptedTextField(blank=True, default="")),
                (
                    "estimate_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("price_cents", models.PositiveIntegerField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customization",
                        to="support.ticket",
                    ),
                ),
            ],
        ),
    ]
