# Generated by Django 5.2.17 on 2026-10-06 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forense", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourtInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tribunal", models.CharField(max_length=12, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "balcao_virtual_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "services_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "hearings_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("hours", models.CharField(blank=True, default="", max_length=120)),
                ("notes", models.CharField(blank=True, default="", max_length=500)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["tribunal"],
            },
        ),
        migrations.CreateModel(
            name="CourtSuspension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tribunal",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=12
                    ),
                ),
                ("comarca", models.CharField(blank=True, default="", max_length=80)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("prazos", "Suspensão de prazos"),
                            ("expediente", "Sem expediente forense"),
                            (
                                "indisponibilidade",
                                "Indisponibilidade do sistema (prorroga prazos)",
                            ),
                        ],
                        default="prazos",
                        max_length=20,
                    ),
                ),
                ("start", models.DateField(db_index=True)),
                ("end", models.DateField()),
                ("reason", models.CharField(max_length=200)),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
            },
        ),
    ]
