# Generated by Django 5.2.17 on 2026-10-05 17:59

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        ("contacts", "0001_initial"),
        ("research", "0002_monitoredcase_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("area", models.CharField(blank=True, default="", max_length=40)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("novo", "Novo contato"),
                            ("qualificacao", "Entendendo o caso"),
                            ("reuniao", "Reunião marcada"),
                            ("proposta", "Proposta enviada"),
                            ("ganho", "Contrato fechado"),
                            ("perdido", "Não fechou"),
                        ],
                        db_index=True,
                        default="novo",
                        max_length=14,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("indicacao", "Indicação"),
                            ("site", "Site / blog"),
                            ("redes", "Redes sociais"),
                            ("google", "Google / Perfil da empresa"),
                            ("cliente", "Cliente da casa"),
                            ("outro", "Outro"),
                        ],
                        default="outro",
                        max_length=12,
                    ),
                ),
                ("value_cents", models.PositiveBigIntegerField(default=0)),
                (
                    "next_action",
                    models.CharField(blank=True, default="", max_length=160),
                ),
                ("next_action_at", models.DateField(blank=True, null=True)),
                (
                    "lost_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notes", core.utils.EncryptedTextField(blank=True, default="")),
                ("stage_changed_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opportunities",
                        to="accounts.organization",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FeeAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("avista", "À vista"),
                            ("parcelado", "Parcelado"),
                            ("mensal", "Mensal (partido/recorrente)"),
                            ("exito", "Êxito (% do proveito)"),
                            ("misto", "Entrada + êxito"),
                        ],
                        max_length=10,
                    ),
                ),
                ("total_cents", models.PositiveBigIntegerField(default=0)),
                ("installments", models.PositiveSmallIntegerField(default=1)),
                ("first_due", models.DateField(blank=True, null=True)),
                (
                    "success_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("encerrado", "Encerrado"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="ativo",
                        max_length=10,
                    ),
                ),
                ("notes", core.utils.EncryptedTextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fee_agreements",
                        to="research.monitoredcase",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_agreements",
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_agreements",
                        to="accounts.organization",
                    ),
                ),
                (
                    "opportunity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="agreements",
                        to="carteira.opportunity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Receivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                ("amount_cents", models.PositiveBigIntegerField()),
                ("due_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("aberto", "Em aberto"),
                            ("pago", "Pago"),
                            ("cancelado", "Cancelado"),
                        ],
                        db_index=True,
                        default="aberto",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateField(blank=True, null=True)),
                ("paid_cents", models.PositiveBigIntegerField(default=0)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("pix", "Pix"),
                            ("boleto", "Boleto"),
                            ("cartao", "Cartão"),
                            ("transferencia", "Transferência"),
                            ("dinheiro", "Dinheiro"),
                            ("outro", "Outro"),
                        ],
                        default="",
                        max_length=14,
                    ),
                ),
                (
                    "asaas_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=40
                    ),
                ),
                (
                    "payment_url",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivables",
                        to="carteira.feeagreement",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receivables",
                        to="research.monitoredcase",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receivables",
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receivables",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("custas", "Custas processuais"),
                            ("diligencia", "Diligência / correspondente"),
                            ("pericia", "Perícia / assistente técnico"),
                            ("deslocamento", "Deslocamento"),
                            ("copias", "Cópias / cartório"),
                            ("escritorio", "Despesa do escritório"),
                            ("outros", "Outros"),
                        ],
                        default="custas",
                        max_length=14,
                    ),
                ),
                ("amount_cents", models.PositiveBigIntegerField()),
                ("date", models.DateField(db_index=True)),
                ("reimbursable", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="research.monitoredcase",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to="contacts.contact",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="accounts.organization",
                    ),
                ),
                (
                    "reimbursement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expense",
                        to="carteira.receivable",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AsaasEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=80)),
                ("event", models.CharField(max_length=40)),
                ("payment_id", models.CharField(blank=True, default="", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "event_id"), name="uniq_asaas_event"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="opportunity",
            index=models.Index(
                fields=["organization", "stage"], name="carteira_op_organiz_eed4f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receivable",
            index=models.Index(
                fields=["organization", "status", "due_date"],
                name="carteira_re_organiz_cf2cf9_idx",
            ),
        ),
    ]
