# Generated by Django 5.2.17 on 2026-10-06 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_access_groups"),
        ("carteira", "0001_initial"),
        ("marketing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="campaign",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="marketing.campaign",
            ),
        ),
        migrations.AddField(
            model_name="receivable",
            name="nfse_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=40
            ),
        ),
        migrations.AddField(
            model_name="receivable",
            name="nfse_status",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="receivable",
            name="nfse_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="FinanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monthly_goal_cents", models.PositiveBigIntegerField(default=0)),
                (
                    "regime",
                    models.CharField(
                        choices=[
                            ("simples", "Simples Nacional (Anexo IV)"),
                            ("presumido", "Lucro Presumido"),
                            ("autonomo", "Advogado autônomo (Carnê-Leão)"),
                            ("uniprofissional", "Sociedade uniprofissional (ISS fixo)"),
                            ("outro", "Outro / não sei"),
                        ],
                        default="outro",
                        max_length=16,
                    ),
                ),
                (
                    "iss_pct",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "service_description",
                    models.CharField(
                        blank=True, default="Honorários advocatícios", max_length=300
                    ),
                ),
                (
                    "municipal_service_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "municipal_service_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "accountant_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="finance_settings",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecurringExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("custas", "Custas processuais"),
                            ("diligencia", "Diligência / correspondente"),
                            ("pericia", "Perícia / assistente técnico"),
                            ("deslocamento", "Deslocamento"),
                            ("copias", "Cópias / cartório"),
                            ("escritorio", "Despesa do escritório"),
                            ("outros", "Outros"),
                        ],
                        default="escritorio",
                        max_length=14,
                    ),
                ),
                ("amount_cents", models.PositiveBigIntegerField()),
                ("day", models.PositiveSmallIntegerField(default=5)),
                ("active", models.BooleanField(default=True)),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("last_month", models.CharField(blank=True, default="", max_length=7)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_expenses",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["day", "description"],
            },
        ),
    ]
