# Generated by Django 5.2.17 on 2026-10-05 12:46

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("enabled", models.BooleanField(default=False)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("document_confirmed", "Documento confirmado"),
                            ("case_movement", "Andamento novo no processo"),
                            ("deadline_soon", "Prazo chegando"),
                            ("contact_created", "Contato cadastrado"),
                            ("schedule", "Agenda (diária/semanal)"),
                        ],
                        max_length=30,
                    ),
                ),
                ("trigger_config", models.JSONField(blank=True, default=dict)),
                ("conditions", models.JSONField(blank=True, default=list)),
                ("actions", models.JSONField(blank=True, default=list)),
                ("require_approval", models.BooleanField(default=True)),
                (
                    "template_key",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "simulated_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("run_count", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automation_rules",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RuleRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger", models.CharField(max_length=30)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Executando"),
                            ("success", "Concluída"),
                            ("partial", "Concluída com falhas"),
                            ("failed", "Falhou"),
                            ("skipped", "Condições não atendidas"),
                            ("pending_approval", "Aguardando aprovação"),
                            ("rejected", "Recusada"),
                            ("expired", "Aprovação expirada"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=20,
                    ),
                ),
                ("title", core.utils.EncryptedTextField(blank=True, default="")),
                ("steps", core.utils.EncryptedJSONField(blank=True, default=list)),
                ("dedupe_key", models.CharField(max_length=120)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="accounts.organization",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="automations.rule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="rule",
            index=models.Index(
                fields=["organization", "trigger", "enabled"],
                name="automations_organiz_2fe106_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulerun",
            constraint=models.UniqueConstraint(
                fields=("rule", "dedupe_key"), name="uniq_rule_run_dedupe"
            ),
        ),
    ]
