# Generated by Django 5.2.17 on 2026-10-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("document_confirmed", "Documento confirmado"),
                    ("case_movement", "Andamento novo no processo"),
                    ("deadline_soon", "Prazo chegando"),
                    ("contact_created", "Contato cadastrado"),
                    ("schedule", "Agenda (diária/semanal)"),
                    ("publication_new", "Publicação nova (DJEN)"),
                ],
                max_length=30,
            ),
        ),
    ]
