# Generated by Django 5.2.17 on 2026-10-05 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0002_alter_rule_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("document_confirmed", "Documento confirmado"),
                    ("case_movement", "Andamento novo no processo"),
                    ("deadline_soon", "Prazo chegando"),
                    ("contact_created", "Contato cadastrado"),
                    ("schedule", "Agenda (diária/semanal)"),
                    ("publication_new", "Publicação nova (DJEN)"),
                    ("receivable_due", "Honorário vencendo ou vencido"),
                ],
                max_length=30,
            ),
        ),
    ]
