# Generated by Django 5.2.17 on 2026-10-06 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0003_alter_rule_trigger"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("document_confirmed", "Documento confirmado"),
                    ("case_movement", "Andamento novo no processo"),
                    ("deadline_soon", "Prazo chegando"),
                    ("contact_created", "Contato cadastrado"),
                    ("schedule", "Agenda (diária/semanal)"),
                    ("publication_new", "Publicação nova (DJEN)"),
                    ("receivable_due", "Honorário vencendo ou vencido"),
                    ("email_received", "E-mail recebido (triado)"),
                    ("calendar_event", "Compromisso da Agenda Google chegando"),
                    ("task_overdue", "Tarefa atrasada"),
                    ("receivable_paid", "Pagamento recebido"),
                    ("opportunity_stage", "Oportunidade mudou de etapa"),
                    ("agreement_created", "Contrato de honorários criado"),
                    ("document_uploaded", "Documento enviado"),
                    ("portal_viewed", "Cliente abriu o portal"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="rulerun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Executando"),
                    ("success", "Concluída"),
                    ("partial", "Concluída com falhas"),
                    ("failed", "Falhou"),
                    ("skipped", "Condições não atendidas"),
                    ("pending_approval", "Aguardando aprovação"),
                    ("rejected", "Recusada"),
                    ("expired", "Aprovação expirada"),
                    ("scheduled", "Agendada (fora do horário comercial)"),
                ],
                db_index=True,
                default="running",
                max_length=20,
            ),
        ),
    ]
