# Generated by Django 5.2.17 on 2026-10-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("automations", "0004_alter_rule_trigger_alter_rulerun_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rule",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("document_confirmed", "Documento confirmado"),
                    ("case_movement", "Andamento novo no processo"),
                    ("deadline_soon", "Prazo chegando"),
                    ("contact_created", "Contato cadastrado"),
                    ("schedule", "Agenda (diária/semanal)"),
                    ("publication_new", "Publicação nova (DJEN)"),
                    ("receivable_due", "Honorário vencendo ou vencido"),
                    ("email_received", "E-mail recebido (triado)"),
                    ("calendar_event", "Compromisso da Agenda Google chegando"),
                    ("task_overdue", "Tarefa atrasada"),
                    ("receivable_paid", "Pagamento recebido"),
                    ("opportunity_stage", "Oportunidade mudou de etapa"),
                    ("agreement_created", "Contrato de honorários criado"),
                    ("document_uploaded", "Documento enviado"),
                    ("portal_viewed", "Cliente abriu o portal"),
                    ("lead_captured", "Contato pelo formulário de captação"),
                    ("survey_answered", "Cliente respondeu a pesquisa de satisfação"),
                    ("nfse_issued", "Nota fiscal de honorários emitida"),
                    ("expense_created", "Despesa lançada"),
                    ("court_suspension", "Suspensão de prazos no tribunal"),
                    ("contact_birthday", "Aniversário do cliente"),
                    ("opportunity_stale", "Oportunidade parada no funil"),
                    ("case_stale", "Processo sem andamento"),
                    ("contract_ending", "Contrato de honorários terminando"),
                    ("monthly_goal", "Acompanhamento da meta do mês"),
                ],
                max_length=30,
            ),
        ),
    ]
