# Generated by Django 5.2.17 on 2026-10-07 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_email_visual"),
        ("automations", "0006_atalho"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("apple", "Apple Watch / iPhone (Siri)"),
                            ("wear", "Android / Wear OS"),
                            ("alexa", "Alexa"),
                            ("google", "Google Assistente"),
                            ("outro", "Outro (botão, NFC, automação)"),
                        ],
                        default="apple",
                        max_length=10,
                    ),
                ),
                ("key_hash", models.CharField(max_length=64, unique=True)),
                ("can_approve", models.BooleanField(default=False)),
                ("notify", models.BooleanField(default=False)),
                ("ntfy_topic", models.CharField(blank=True, default="", max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_devices",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
