# Generated by Django 5.2.14 on 2026-09-25 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_usermessagesendcount_dashboard_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cliente', models.CharField(blank=True, default='', max_length=255)),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('peticao', 'Petição'), ('procuracao', 'Procuração'), ('outro', 'Outro')], default='outro', max_length=50)),
                ('status', models.CharField(choices=[('processando', 'Processando'), ('pronto', 'Pronto'), ('aguardando_assinatura', 'Aguardando assinatura'), ('assinado', 'Assinado')], default='processando', max_length=50)),
                ('data', models.DateField(blank=True, null=True)),
                ('arquivo', models.FileField(blank=True, upload_to='documents/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.organization')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'nome'], name='documents_d_organiz_d5514e_idx'), models.Index(fields=['organization', 'status'], name='documents_d_organiz_b8cccc_idx')],
            },
        ),
    ]
