# Generated by Django 5.2.14 on 2026-09-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='document',
            name='arquivo',
            field=models.FileField(upload_to='documents/%Y/%m/'),
        ),
    ]
