# Generated by Django 5.2.14 on 2026-09-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_links', to='documents.document')),
            ],
            options={
                'verbose_name': 'Documento do cliente',
                'verbose_name_plural': 'Documentos do cliente',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['nome_cliente'], name='documents_c_nome_cl_65efe1_idx')],
            },
        ),
    ]
