# Generated by Django 5.2.14 on 2026-09-25 17:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_client_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='arquivo',
            field=models.FileField(max_length=500, upload_to='documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
