# Generated by Django 5.2.17 on 2026-10-04 15:23

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_fix_arquivo_max_length_and_data_now"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="clientdocument",
            name="documents_c_nome_cl_65efe1_idx",
        ),
        migrations.AddField(
            model_name="clientdocument",
            name="nome_cliente_idx",
            field=models.TextField(blank=True, default="", editable=False),
        ),
        migrations.AlterField(
            model_name="clientdocument",
            name="nome_cliente",
            field=core.utils.EncryptedTextField(),
        ),
    ]
