# Generated by Django 5.2.17 on 2026-10-04 16:58

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0006_backfill_pii"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="arquivo",
            field=models.FileField(
                max_length=500,
                storage=core.storage.encrypted_storage,
                upload_to="documents/%Y/%m/",
            ),
        ),
    ]
