# Generated by Django 5.2.17 on 2026-10-04 16:59

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0007_encrypted_files"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Na fila"),
                            ("processing", "Processando"),
                            ("review", "Aguardando revisão"),
                            ("confirmed", "Confirmado"),
                            ("failed", "Falhou"),
                            ("skipped", "Não processado"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("stage", models.CharField(blank=True, default="", max_length=20)),
                (
                    "detected_kind",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("text_chars", models.PositiveIntegerField(default=0)),
                ("ocr_used", models.BooleanField(default=False)),
                ("provider", models.CharField(blank=True, default="", max_length=10)),
                ("confidence", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("fields", core.utils.EncryptedJSONField(blank=True, default=dict)),
                ("message", models.CharField(blank=True, default="", max_length=255)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extraction",
                        to="documents.document",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
