# Generated by Django 5.2.17 on 2026-10-04 17:08

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0008_document_extraction"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentextraction",
            name="auto_task_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="documentextraction",
            name="excerpt",
            field=core.utils.EncryptedTextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="documentextraction",
            name="original_fields",
            field=core.utils.EncryptedJSONField(blank=True, default=dict),
        ),
    ]
