# Generated by Django 5.2.17 on 2026-10-02 19:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0005_usermessagesendcount_dashboard_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalAISwitch",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("ai_enabled", models.BooleanField(default=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("changed_by", models.CharField(blank=True, max_length=64)),
                ("changed_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="AIActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("organization_id", models.UUIDField(db_index=True, null=True)),
                ("user_ref", models.CharField(blank=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("extraction", "Extração de dados"),
                            ("workflow_generation", "Geração de workflow"),
                        ],
                        max_length=24,
                    ),
                ),
                ("provider", models.CharField(max_length=16)),
                ("data_categories", models.JSONField(default=list)),
                ("input_chars", models.PositiveIntegerField(default=0)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("blocked", models.BooleanField(default=False)),
                ("block_reason", models.CharField(blank=True, max_length=64)),
                ("request_id", models.CharField(blank=True, max_length=64)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization_id", "created_at"],
                        name="aigov_aiact_organiz_066379_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIGovernancePolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ai_enabled",
                    models.BooleanField(
                        default=True, help_text="Kill switch do escritório."
                    ),
                ),
                (
                    "autonomy_level",
                    models.CharField(
                        choices=[
                            ("off", "Desligada — nenhuma chamada de IA"),
                            (
                                "suggest",
                                "Somente sugestões — IA gera rascunhos; nada executa sem confirmação humana",
                            ),
                            (
                                "supervised",
                                "Supervisionada (padrão) — rascunhos exigem aprovação; ações externas de origem IA exigem confirmação",
                            ),
                            (
                                "autonomous_limited",
                                "Autonomia limitada — workflows aprovados executam sozinhos (aprovação de rascunhos continua obrigatória)",
                            ),
                        ],
                        default="supervised",
                        max_length=24,
                    ),
                ),
                (
                    "allowed_providers",
                    models.JSONField(
                        default=list,
                        help_text="Provedores permitidos: OPENAI, GEMINI, GROQ.",
                    ),
                ),
                ("daily_ai_request_limit", models.PositiveIntegerField(default=500)),
                (
                    "max_actions_per_ai_workflow",
                    models.PositiveSmallIntegerField(default=5),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.CharField(blank=True, max_length=64)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_policy",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
    ]
