# Generated by Django 5.2.17 on 2026-10-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aigov", "0002_alter_aiactionlog_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiactionlog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("extraction", "Extração de dados"),
                    ("workflow_generation", "Geração de workflow"),
                    ("triage", "Triagem de publicação"),
                    ("draft", "Minuta"),
                    ("marketing", "Conteúdo de marketing"),
                ],
                max_length=24,
            ),
        ),
    ]
