# Generated by Django 5.2.17 on 2026-10-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aigov", "0003_alter_aiactionlog_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiactionlog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("extraction", "Extração de dados"),
                    ("workflow_generation", "Geração de workflow"),
                    ("triage", "Triagem de publicação"),
                    ("draft", "Minuta"),
                    ("marketing", "Conteúdo de marketing"),
                    ("assistant", "Assistente (conversa e comandos)"),
                    ("writing", "Escrita (corrigir, reescrever, resumir)"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="aigovernancepolicy",
            name="allowed_providers",
            field=models.JSONField(
                default=list,
                help_text="Provedores permitidos (chaves de aigov.llm.PROVIDERS).",
            ),
        ),
    ]
