# Generated by Django 5.2.17 on 2026-10-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aigov", "0004_alter_aiactionlog_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("activity", models.CharField(max_length=20, unique=True)),
                ("providers", models.JSONField(default=list)),
                ("use_reserves", models.BooleanField(default=True)),
                (
                    "updated_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
