# Generated by Django 5.2.17 on 2026-10-02 19:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnomalyAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("rule", models.CharField(db_index=True, max_length=32)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Baixa"),
                            ("medium", "Média"),
                            ("high", "Alta"),
                            ("critical", "Crítica"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Aberto"),
                            ("ack", "Em análise"),
                            ("resolved", "Resolvido"),
                            ("false_positive", "Falso positivo"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=16,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("actor_label", models.CharField(blank=True, max_length=255)),
                (
                    "organization_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("summary", models.CharField(max_length=255)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("dedupe_key", models.CharField(max_length=128, unique=True)),
                ("reviewed_by", models.CharField(blank=True, max_length=64)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuditChainHead",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, primary_key=True, serialize=False
                    ),
                ),
                ("last_seq", models.BigIntegerField(default=0)),
                (
                    "last_hash",
                    models.CharField(
                        default="0000000000000000000000000000000000000000000000000000000000000000",
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AuditCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("purged_until_seq", models.BigIntegerField()),
                ("last_hash", models.CharField(max_length=64)),
                ("purged_count", models.PositiveIntegerField()),
                ("reason", models.CharField(default="retention", max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                ("seq", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "request_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "actor_type",
                    models.CharField(
                        choices=[
                            ("user", "Utilizador"),
                            ("admin", "Administrador (staff)"),
                            ("system", "Sistema/worker"),
                            ("webhook", "Webhook externo"),
                            ("anonymous", "Anónimo"),
                        ],
                        default="anonymous",
                        max_length=16,
                    ),
                ),
                (
                    "actor_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "actor_label",
                    models.CharField(
                        blank=True,
                        help_text="E-mail mascarado (j***@dominio).",
                        max_length=255,
                    ),
                ),
                (
                    "organization_id",
                    models.UUIDField(blank=True, db_index=True, null=True),
                ),
                (
                    "action",
                    models.CharField(
                        db_index=True,
                        help_text="categoria.verbo, ex.: auth.login.success",
                        max_length=64,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=64)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Sucesso"),
                            ("denied", "Negado"),
                            ("error", "Erro"),
                        ],
                        default="success",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent_hash", models.CharField(blank=True, max_length=16)),
                ("auth_method", models.CharField(blank=True, max_length=32)),
                (
                    "changes",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Só nomes de campos/metadados — nunca valores pessoais.",
                    ),
                ),
                ("data_categories", models.JSONField(blank=True, default=list)),
                ("legal_basis", models.CharField(blank=True, max_length=32)),
                ("prev_hash", models.CharField(editable=False, max_length=64)),
                ("hash", models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "Evento de auditoria",
                "verbose_name_plural": "Eventos de auditoria",
                "ordering": ["seq"],
                "indexes": [
                    models.Index(
                        fields=["organization_id", "occurred_at"],
                        name="audit_audit_organiz_950f33_idx",
                    ),
                    models.Index(
                        fields=["actor_id", "occurred_at"],
                        name="audit_audit_actor_i_023a4b_idx",
                    ),
                    models.Index(
                        fields=["action", "occurred_at"],
                        name="audit_audit_action_7e10a4_idx",
                    ),
                ],
            },
        ),
    ]
