# Generated by Django 5.2.17 on 2026-10-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_immutability_triggers"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedIP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "network",
                    models.CharField(
                        help_text="IP (203.0.113.7) ou faixa CIDR (203.0.113.0/24).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("created_by", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Vazio = até a TI remover.", null=True
                    ),
                ),
                ("hits", models.PositiveIntegerField(default=0)),
                ("last_hit_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "IP bloqueado",
                "verbose_name_plural": "IPs bloqueados",
                "ordering": ["-created_at"],
            },
        ),
    ]
