# Generated by Django 5.2.17 on 2026-10-02 19:34

import core.utils
from django.db import migrations


def encrypt_existing(apps, schema_editor):
    """Re-grava as linhas: tokens legados em texto puro passam a ficar cifrados."""
    Model = apps.get_model('tasks', 'IntegrationConfig')
    for obj in Model.objects.all().iterator():
        obj.save(update_fields=['trello_api_key', 'trello_api_token', 'telegram_bot_token'])


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_usertask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationconfig",
            name="telegram_bot_token",
            field=core.utils.EncryptedTextField(
                blank=True, verbose_name="Telegram Bot Token"
            ),
        ),
        migrations.AlterField(
            model_name="integrationconfig",
            name="trello_api_key",
            field=core.utils.EncryptedTextField(
                blank=True, verbose_name="Trello API Key"
            ),
        ),
        migrations.AlterField(
            model_name="integrationconfig",
            name="trello_api_token",
            field=core.utils.EncryptedTextField(
                blank=True, verbose_name="Trello API Token"
            ),
        ),
        migrations.RunPython(encrypt_existing, migrations.RunPython.noop),
    ]
