# Generated by Django 5.2.17 on 2026-10-05 13:20

import core.pii
import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0013_mfa"),
        ("research", "0002_monitoredcase_client"),
        ("tasks", "0003_encrypt_integration_tokens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OabWatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=10)),
                ("uf", models.CharField(max_length=2)),
                ("nome", models.CharField(blank=True, default="", max_length=120)),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="oab_watches",
                        to="accounts.organization",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["uf", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(default="djen", max_length=10)),
                ("external_id", models.CharField(max_length=64)),
                ("tribunal", models.CharField(blank=True, default="", max_length=20)),
                ("tipo", models.CharField(blank=True, default="", max_length=80)),
                ("orgao", models.CharField(blank=True, default="", max_length=255)),
                ("classe", models.CharField(blank=True, default="", max_length=255)),
                ("cnj", core.utils.EncryptedTextField(blank=True, default="")),
                (
                    "cnj_bidx",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        max_length=64,
                        null=True,
                    ),
                ),
                ("texto", core.utils.EncryptedTextField(blank=True, default="")),
                ("partes", core.utils.EncryptedJSONField(blank=True, default=list)),
                ("link", models.URLField(blank=True, default="", max_length=500)),
                ("disponibilizada_em", models.DateField(db_index=True)),
                ("publicada_em", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("nova", "Nova"),
                            ("confirmada", "Confirmada"),
                            ("descartada", "Descartada"),
                        ],
                        db_index=True,
                        default="nova",
                        max_length=12,
                    ),
                ),
                ("triage", core.utils.EncryptedJSONField(blank=True, default=dict)),
                ("vencimento", models.DateField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_note",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="research.monitoredcase",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publications",
                        to="accounts.organization",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tasks.usertask",
                    ),
                ),
                (
                    "watch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="publications",
                        to="publications.oabwatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-disponibilizada_em", "-pk"],
            },
            bases=(core.pii.PIIIndexMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name="oabwatch",
            constraint=models.UniqueConstraint(
                fields=("organization", "numero", "uf"), name="uniq_oab_watch_per_org"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["organization", "status", "-disponibilizada_em"],
                name="publication_organiz_96cd28_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                fields=("organization", "external_id"), name="uniq_publication_per_org"
            ),
        ),
    ]
