# Generated by Django 5.2.17 on 2026-10-05 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_encrypt_secrets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appconnection",
            name="app_name",
            field=models.CharField(
                choices=[
                    ("WHATSAPP", "WhatsApp (API Meta/Evolution)"),
                    ("SHEETS", "Google Sheets"),
                    ("CLICKUP", "ClickUp"),
                    ("TRELLO", "Trello"),
                    ("TELEGRAM", "Telegram"),
                    ("ASTREA", "Astrea (Sistema Jurídico)"),
                    ("WEBHOOK", "Webhook Customizado"),
                    ("SMTP", "E-mail do escritório (SMTP)"),
                    ("ZAPSIGN", "ZapSign (assinatura eletrônica)"),
                    ("ASAAS", "Asaas (boleto e Pix)"),
                    ("META", "Facebook e Instagram (Meta)"),
                ],
                max_length=50,
                verbose_name="Aplicativo",
            ),
        ),
    ]
