# Generated by Django 5.2.12 on 2026-03-23 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_integrationconfig_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Conexão (ex: WhatsApp do Suporte)')),
                ('app_name', models.CharField(choices=[('WHATSAPP', 'WhatsApp (API Meta/Evolution)'), ('SHEETS', 'Google Sheets'), ('CLICKUP', 'ClickUp'), ('TRELLO', 'Trello'), ('TELEGRAM', 'Telegram'), ('ASTREA', 'Astrea (Sistema Jurídico)'), ('WEBHOOK', 'Webhook Customizado')], max_length=50, verbose_name='Aplicativo')),
                ('credentials', models.JSONField(default=dict, help_text='Credenciais no formato JSON. (Deverão ser encriptadas no banco!)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Conexão de App',
                'verbose_name_plural': 'Conexões de Apps',
            },
        ),
        migrations.RemoveField(
            model_name='integrationconfig',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='integrationlog',
            options={'ordering': ['-attempted_at'], 'verbose_name': 'Log de Integração', 'verbose_name_plural': 'Logs de Integração'},
        ),
        migrations.RemoveIndex(
            model_name='integrationlog',
            name='integration_email_m_9e4b33_idx',
        ),
        migrations.RemoveField(
            model_name='integrationlog',
            name='email_message',
        ),
        migrations.RemoveField(
            model_name='integrationlog',
            name='service',
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appconnection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to=settings.AUTH_USER_MODEL, verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='integrationlog',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.appconnection'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['connection', 'status'], name='integration_connect_d59868_idx'),
        ),
        migrations.DeleteModel(
            name='IntegrationConfig',
        ),
        migrations.AlterUniqueTogether(
            name='appconnection',
            unique_together={('user', 'name')},
        ),
    ]
