# Generated by Django 5.2.17 on 2026-10-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_alter_appconnection_app_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appconnection",
            name="app_name",
            field=models.CharField(
                choices=[
                    ("WHATSAPP", "WhatsApp (API Meta/Evolution)"),
                    ("SHEETS", "Google Sheets"),
                    ("CLICKUP", "ClickUp"),
                    ("TRELLO", "Trello"),
                    ("TELEGRAM", "Telegram"),
                    ("ASTREA", "Astrea (Sistema Jurídico)"),
                    ("WEBHOOK", "Webhook Customizado"),
                    ("SMTP", "E-mail do escritório (SMTP)"),
                    ("ZAPSIGN", "ZapSign (assinatura eletrônica)"),
                    ("ASAAS", "Asaas (boleto e Pix)"),
                    ("META", "Facebook e Instagram (Meta)"),
                    ("D4SIGN", "D4Sign (assinatura eletrônica)"),
                    ("CLICKSIGN", "Clicksign (assinatura eletrônica)"),
                    ("ESCAVADOR", "Escavador (dados processuais)"),
                    ("NOTION", "Notion"),
                    ("PIPEDRIVE", "Pipedrive (CRM)"),
                    ("CALENDLY", "Calendly (agendamento)"),
                    ("SLACK", "Slack"),
                    ("TEAMS", "Microsoft Teams"),
                    ("JUDIT", "Judit (dados processuais)"),
                    ("JUSBRASIL", "Jusbrasil Soluções"),
                    ("AUTENTIQUE", "Autentique (assinatura eletrônica)"),
                    ("NFEIO", "NFE.io (NFS-e)"),
                    ("OMIE", "Omie (ERP)"),
                    ("BREVO", "Brevo (e-mail)"),
                    ("MAILCHIMP", "Mailchimp"),
                    ("RDSTATION", "RD Station Marketing"),
                    ("ZOOM", "Zoom"),
                    ("ZENVIA", "Zenvia (SMS/WhatsApp)"),
                ],
                max_length=50,
                verbose_name="Aplicativo",
            ),
        ),
    ]
