# Generated by Django 5.2.17 on 2026-10-06 12:38

import core.utils
import django.db.models.deletion
import gcal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_customuser_must_change_password"),
        ("contacts", "0001_initial"),
        ("gcal", "0001_initial"),
        ("research", "0002_monitoredcase_client"),
        ("tasks", "0003_encrypt_integration_tokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarlink",
            name="events_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="googlecalendarlink",
            name="import_events",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="googlecalendarlink",
            name="lookahead_days",
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="googlecalendarlink",
            name="task_kinds",
            field=models.JSONField(
                blank=True,
                default=gcal.models.default_task_kinds,
                help_text="Tipos que viram tarefa no Cadrius (prazo, audiencia…).",
            ),
        ),
        migrations.CreateModel(
            name="ExternalEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255)),
                ("title", core.utils.EncryptedTextField(blank=True, default="")),
                ("description", core.utils.EncryptedTextField(blank=True, default="")),
                ("location", core.utils.EncryptedTextField(blank=True, default="")),
                ("start", models.DateTimeField(db_index=True)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("all_day", models.BooleanField(default=False)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("prazo", "Prazo"),
                            ("audiencia", "Audiência"),
                            ("reuniao", "Reunião / atendimento"),
                            ("pericia", "Perícia / diligência"),
                            ("outro", "Outro compromisso"),
                        ],
                        db_index=True,
                        default="outro",
                        max_length=10,
                    ),
                ),
                ("kind_locked", models.BooleanField(default=False)),
                ("cancelled", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="research.monitoredcase",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contacts.contact",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_events",
                        to="gcal.googlecalendarlink",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_events",
                        to="accounts.organization",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="tasks.usertask",
                    ),
                ),
            ],
            options={
                "ordering": ["start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("link", "event_id"), name="uniq_external_event_per_link"
                    )
                ],
            },
        ),
    ]
