# Generated by Django 5.2.17 on 2026-10-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcal", "0002_external_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarapp",
            name="uses_platform",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="googlecalendarlink",
            name="google_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="googlecalendarlink",
            name="scopes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
