# Generated by Django 5.2.17 on 2026-10-08 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcal", "0003_google_plataforma"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("sheet", "Planilha"), ("doc", "Documento")],
                        max_length=5,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file_id", models.CharField(max_length=200)),
                ("url", models.URLField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(auto_now=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="gcal.googlecalendarlink",
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("link", "kind", "name"), name="uniq_google_file_name"
                    )
                ],
            },
        ),
    ]
