# Generated by Django 5.2.17 on 2026-10-04 17:19

import core.pii
import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0012_backfill_pii"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.CharField(max_length=80)),
                ("url", models.URLField(max_length=500, unique=True)),
                ("title", models.CharField(max_length=300)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="MonitoredCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cnj", core.utils.EncryptedTextField()),
                (
                    "cnj_bidx",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                ("tribunal", models.CharField(max_length=12)),
                ("label", core.utils.EncryptedTextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_movement_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_error",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitored_cases",
                        to="accounts.organization",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(core.pii.PIIIndexMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CaseMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("occurred_at", models.DateTimeField(blank=True, null=True)),
                ("code", models.CharField(blank=True, default="", max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "complement",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("digest", models.CharField(max_length=40)),
                ("notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="research.monitoredcase",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="monitoredcase",
            constraint=models.UniqueConstraint(
                fields=("organization", "cnj_bidx"), name="uniq_case_per_org"
            ),
        ),
        migrations.AddConstraint(
            model_name="casemovement",
            constraint=models.UniqueConstraint(
                fields=("case", "digest"), name="uniq_movement_per_case"
            ),
        ),
    ]
