# Generated by Django 5.2.17 on 2026-10-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoredcase",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="contacts.contact",
            ),
        ),
    ]
