# Generated by Django 5.2.17 on 2026-10-06 12:51

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_customuser_must_change_password"),
        ("assistant", "0001_initial"),
        ("contacts", "0001_initial"),
        ("research", "0002_monitoredcase_client"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="research.monitoredcase",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contacts.contact",
            ),
        ),
        migrations.AddField(
            model_name="conversation",
            name="mode",
            field=models.CharField(
                choices=[
                    ("geral", "Assistente"),
                    ("caso", "Estratégia de caso"),
                    ("mcp", "Pedidos pelo conector (Claude/ChatGPT)"),
                ],
                default="geral",
                max_length=6,
            ),
        ),
        migrations.CreateModel(
            name="AssistantSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "case_strategy",
                    models.BooleanField(
                        default=False,
                        help_text='Modo "estratégia de caso" disponível para a equipe.',
                    ),
                ),
                (
                    "mcp_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Permite ligar o conector do Cadrius no Claude/ChatGPT.",
                    ),
                ),
                (
                    "use_memory",
                    models.BooleanField(
                        default=True,
                        help_text="O assistente consulta a memória do escritório em cada pergunta.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assistant_settings",
                        to="accounts.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("prefix", models.CharField(max_length=12)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("leitura", "Só consultar"),
                            (
                                "pedidos",
                                "Consultar e preparar pedidos (confirmados no Cadrius)",
                            ),
                        ],
                        default="leitura",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("uses", models.PositiveIntegerField(default=0)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_tokens",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrgAIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=16)),
                ("api_key", core.utils.EncryptedTextField()),
                ("base_url", models.CharField(blank=True, default="", max_length=255)),
                ("model", models.CharField(blank=True, default="", max_length=80)),
                (
                    "paid_account",
                    models.BooleanField(
                        default=True,
                        help_text="Conta paga (provedor não treina com os dados).",
                    ),
                ),
                ("last4", models.CharField(blank=True, default="", max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_keys",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "provider"),
                        name="uniq_ai_key_per_org_provider",
                    )
                ],
            },
        ),
    ]
