name: Cadrius AI - CI/CD

# Quando este robô deve rodar?
on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-validate:
    name: Construção e Validação
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar o repositório
      uses: actions/checkout@v4

    - name: ⚙️ Criar arquivo .env de Teste
      # Como o .env real não vai pro GitHub, criamos um falso só para o teste passar
      run: |
        echo "DEBUG=True" > .env
        echo "SECRET_KEY=chave_secreta_para_ci_teste_123" >> .env
        echo "ENCRYPTION_KEY=CHAVE_FALSA_PARA_TESTE_DE_32_BYTES_===" >> .env
        echo "DATABASE_URL=postgres://postgres:postgres@db:5432/cadrius" >> .env
        echo "REDIS_URL=redis://redis:6379/0" >> .env
        echo "NGROK_AUTHTOKEN=dummy_token_ci" >> .env

    - name: 🐳 Subir a Infraestrutura Core (Docker)
      # Sobe apenas o essencial para testar o código (ignora ngrok, dozzle e backup aqui)
      run: docker compose up -d db redis web

    - name: ⏳ Aguardar o banco de dados iniciar
      run: sleep 10

    - name: 🕵️ Checar integridade do Django (Erros de Sintaxe)
      run: docker compose exec -T web python manage.py check

    - name: 🗃️ Checar se esqueceram migrações (Database)
      # Se alguém alterou um Model e esqueceu do makemigrations, o CI vai falhar!
      run: docker compose exec -T web python manage.py makemigrations --check --dry-run