# Generated by Django 5.2.14 on 2026-10-01 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_organization_next_billing_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('documento', 'Documento'), ('prazo', 'Prazo'), ('automacao', 'Automação'), ('erro', 'Erro')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('origem', models.CharField(blank=True, default='', max_length=100)),
                ('documento', models.CharField(blank=True, default='', max_length=255)),
                ('acao', models.CharField(blank=True, default='', max_length=255)),
                ('detalhes', models.TextField(blank=True, default='')),
                ('action_label', models.CharField(blank=True, default='', max_length=100)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('dedupe_key', models.CharField(blank=True, default='', max_length=255)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='notification_unique_user_dedupe_key')],
            },
        ),
    ]
