# Generated by Django 5.2.17 on 2026-10-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("documento", "Documento"),
                    ("prazo", "Prazo"),
                    ("automacao", "Automação"),
                    ("erro", "Erro"),
                    ("suporte", "Suporte"),
                ],
                max_length=20,
            ),
        ),
    ]
